### ISSUE TITLE
 nipejs: command not found

### ISSUE THREAD

**Issue by Pessword** [i5nipe/nipejs#5]
After i used go link i found nothing !!

**Comment by i5nipe** [comment]
To install nipejs, use the following command:

```bash
go install github.com/i5nipe/nipejs@latest
```
After installation, you can run nipejs from the command line.

The binary will be installed in the default Go binary directory. Ensure that this directory is included in your system's PATH variable to execute the nipejs command from any location in the terminal.

```bash
export PATH=$PATH:$(go env GOPATH)/bin
```

Please let me know if this solves your issue 😁.

**Comment by Pessword** [comment]
Great :)
