### ISSUE TITLE
Do I have to add urls or ip in the text file

### ISSUE THREAD

**Issue by krivadna** [i5nipe/nipejs#6]

**Comment by i5nipe** [comment]
Currently, if you try to use an IP address like `192.168.0.5`, it will not work (this will be addressed in the next update). The tool expects URLs or files as input.

Your can use the `-d` option to specify a **folder** or a **file** as input:
```
nipejs -d /tmp 
nipejs -d /tmp/random_file.txt
```
Alternatively, you can use the `-u` option, which expects a file containing a list of URLs:
```
cat  urls.txt
https://blog.i5nipe.com/about/
https://blog.i5nipe.com/

nipejs -u urls.txt
```
If you have only one URL to test, you can send it via **STDIN**:
```
echo "https://blog.i5nipe.com/" | nipejs
```

**Comment by krivadna** [comment]
Thank you for replying, nope js is in go/bin directory and all go programs will have to run with bash command so this command echo "https://blog.i5nipe.com/" | ./nipejs gives lot of results but when I use other urls then 

~/go/bin $ echo "https://cm.com/" | ./nipejs
 ███▄    █  ██▓ ██▓███  ▓█████ ▄▄▄██▀▀▀██████
 ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀   ▒██ ▒██    ▒
▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███     ░██ ░ ▓██▄
▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄▓██▄██▓  ▒   ██▒
▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒▓███▒ ▒██████▒▒
░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░▒▓▒▒░ ▒ ▒▓▒ ▒ ░
░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░▒ ░▒░ ░ ░▒  ░ ░
   ░   ░ ░  ▒ ░░░          ░   ░ ░ ░ ░  ░  ░
         ░  ░              ░  ░░   ░       ░


[INF] Nipejs done: 1 files with 190 regex patterns scanned in 0.28 seconds
~/go/bin $

**Comment by i5nipe** [comment]
I see the issue now. It seems to be a race condition causing the tool to return before receiving the results. Thanks for letting me know; I'll work on fixing this.

**Comment by i5nipe** [comment]
It turns out that the URLs are giving timeouts, so `nipejs` could not access the contents to match the request. I changed the default request timeout from 10 seconds to **30 seconds** and added an error message to let users know when a URL gives a timeout error.

Thank you for opening the issue! Please update the nipejs version by running:
`go install github.com/i5nipe/nipejs@latest`

**Comment by krivadna** [comment]
I scanned urls and it's working 

~/go/bin $ ./nipejs -u urls.txt
 ███▄    █  ██▓ ██▓███  ▓█████ ▄▄▄██▀▀▀██████
 ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀   ▒██ ▒██    ▒
▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███     ░██ ░ ▓██▄
▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄▓██▄██▓  ▒   ██▒
▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒▓███▒ ▒██████▒▒
░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░▒▓▒▒░ ▒ ▒▓▒ ▒ ░
░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░▒ ░▒░ ░ ░▒  ░ ░
   ░   ░ ░  ▒ ░░░          ░   ░ ░ ░ ░  ░  ░
         ░  ░              ░  ░░   ░       ░


[*] https://example.com [1.256 B]
Regex:  https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)  URL
        "https://www.iana.org/domains/example"

[INF] Nipejs done: 3 files with 190 regex patterns scanned in 0.94 seconds

Also the problem was in domain, simple url also working now...do I have to add additional regex and can u teach me how to read the results?

**Comment by i5nipe** [comment]
Yes, if you need different regexes, you can use the -r option to specify a file with a list of regexes:
```
❯ cat regexs.txt
(eyJ|YTo|Tzo|PD[89]|aHR0cHM6L|aHR0cDo|rO0)[a-zA-Z0-9+/]+={0,2}		Base64
bearer [a-zA-Z0-9_\\-\\.=]+

❯ nipejs -d index.html -r regexs.txt
```
The string "Base64" after the regex specifies the category, helping you understand what the regex is for. Regex and categories are separated by `\t\t` (two tab characters). To ensure nipejs reads the categories correctly, use:
`❯ nipejs -r regexs.txt -v`
![categories](https://github.com/i5nipe/nipejs/assets/77520996/ead9be74-9fad-4d9b-98b2-58ff336e1b89)

If you only need to add regexes to the default regexes of nipejs, you can do so by putting them in the file ~/.config/nipejs/regex.txt.

# Reading the Results 
I highly recommend using nipejs in a terminal that supports colors.
- The first output is an ASCII art banner, which can be hidden using the -s option.
```
 ███▄    █  ██▓ ██▓███  ▓█████ ▄▄▄██▀▀▀██████
 ██ ▀█   █ ▓██▒▓██░  ██▒▓█   ▀   ▒██ ▒██    ▒
▓██  ▀█ ██▒▒██▒▓██░ ██▓▒▒███     ░██ ░ ▓██▄
▓██▒  ▐▌██▒░██░▒██▄█▓▒ ▒▒▓█  ▄▓██▄██▓  ▒   ██▒
▒██░   ▓██░░██░▒██▒ ░  ░░▒████▒▓███▒ ▒██████▒▒
░ ▒░   ▒ ▒ ░▓  ▒▓▒░ ░  ░░░ ▒░ ░▒▓▒▒░ ▒ ▒▓▒ ▒ ░
░ ░░   ░ ▒░ ▒ ░░▒ ░      ░ ░  ░▒ ░▒░ ░ ░▒  ░ ░
   ░   ░ ░  ▒ ░░░          ░   ░ ░ ░ ░  ░  ░
         ░  ░              ░  ░░   ░       ░

```
- The next line shows the location of the find (URL or file) and its content length. The larger the file, the longer nipejs will take to scan.
`[*] index.html [74 B]`

- The regex that matched will be displayed next. If specified, the category will be shown in green.
`Regex:  bearer [a-zA-Z0-9_\\-\\.=]+  `

- The final line shows the actual string that matched the regex.
`	"bearer secrettoken345"`

Here is a detailed example with colors and categories:
![nipejs_ex](https://github.com/i5nipe/nipejs/assets/77520996/0b7d9a23-5965-4571-8e7a-7f772c450c8a)


Hope this helps! Thanks for using nipejs :)
